### ISSUE TITLE
Add organization to reference page of pkgdown

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tdaverse/tdarec#16]
I would add a `_pkgdown.yml` file using something like this format. You can use the fact that you prefix your steps to your advantage by using `starts_with()`

```yaml
template:
  bootstrap: 5

reference:
- title: pd
  contents:
    - starts_with("step_pd_")
- title: vpd
  contents:
    - starts_with("step_vpd_")
- title: other
  contents:
    - step_blur
    - blur
    - blur_sigmas
    - get_blur_range
    - vpd-finalizers
    - vpd-summarizers
- title: Dials objects
  contents:
    - vpd-dials
- title: Data
  contents:
    - mnist
```
